# Generated by Django 6.0.2 on 2026-02-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_data_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shift_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shify_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
