# Generated by Django 6.0.2 on 2026-02-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('Visa', 'Visa'), ('Cash', 'Cash')], max_length=255)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], max_length=255)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
