# Generated by Django 6.0.2 on 2026-02-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('Private Room', 'Private Room'), ('Semi-Private Rooms', 'Semi-Private Room'), ('Ward Room', 'Ward Room'), ('Suites/VIP Room', 'Suites/VIP Room'), ('Procedure/Treatment Room', 'Procedure/Treatment Room')], max_length=255)),
                ('admission_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField()),
                ('nursing_progress_notes', models.TextField(max_length=1500)),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
