# Generated by Django 6.0.2 on 2026-02-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('test_category', models.CharField(max_length=255)),
                ('normal_range', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(choices=[('mg/dL', 'mg/dL'), ('mmol/L', 'mmol/L'), ('mEq/L', 'mEq/L'), ('µmol/L', 'µmol/L'), ('µU/mL', 'µU/mL')], max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
