# Generated by Django 6.0.2 on 2026-02-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='test_category',
            field=models.CharField(choices=[('Hematology', 'Hematology'), ('Clinical Chemistry', 'Clinical Chemistry'), ('Immunology/Serology', 'Immunology/Serology'), ('Urinalysis', 'Urinalysis'), ('Toxicology', 'Toxicology')], max_length=255),
        ),
    ]
