# Generated by Django 6.0.2 on 2026-02-18 12:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('analgesics', 'analgesics'), ('antibiotics', 'antibiotics'), ('cardiovascular agents', 'cardiovascular agents'), ('antidepressants', 'antidepressants'), ('antidiabetics', 'antidiabetics')], max_length=255)),
                ('strength', models.CharField(choices=[('Low Strength', 'Low Strength'), ('Extra Strength', 'Extra Strength'), ('Double Strength', 'Double Strength')], max_length=255)),
                ('dosage_form', models.CharField(choices=[('Tablets', 'Tablets'), ('Capsules', 'Capsules'), ('Cream', 'Cream'), ('Ointment', 'Ointment'), ('Eye Drops', 'Eye Drops')], max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reorder_level', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expiry_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.datetime.today)])),
                ('manufacturer', models.CharField(choices=[('Merck & Co', 'Merck & Co'), ('Pfizer', 'Pfizer'), ('AbbVie', 'AbbVie'), ('AstraZeneca', 'AstraZeneca')], max_length=255)),
            ],
            options={
                'ordering': ['fullname'],
            },
        ),
    ]
