# Generated by Django 6.0.2 on 2026-02-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], verbose_name='Status')),
                ('patient_notification_status', models.BooleanField(default=False, verbose_name='Notification Status')),
                ('reminder_time', models.DateTimeField(blank=True, null=True, verbose_name='Reminder Time')),
            ],
        ),
    ]
