# Generated by Django 6.0.2 on 2026-02-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('Critical Care', 'Critical Care'), ('Emergency', 'Emergency'), ('Oncology', 'Oncology'), ('Pediatrics', 'Pediatrics'), ('Geriatrics', 'Geriatrics')], max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('shift_type', models.CharField(choices=[('morning', 'morning'), ('afternoon / evening', 'afternoon / evening'), ('night', 'night')], max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
