# Generated by Django 6.0.2 on 2026-02-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'morning'), ('afternoon/evening', 'afternoon/evening'), ('night', 'night')], max_length=255),
        ),
    ]
