# Generated by Django 6.0.2 on 2026-02-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('Internists', 'Internists'), ('Nephrologists', 'Nephrologists'), ('Osteopaths', 'Osteopaths'), ('Pathologists', 'Pathologists')], max_length=255)),
                ('license_number', models.IntegerField()),
                ('phone_number', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('working_days', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')])),
                ('consultation_fee', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
